<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="stylesheet" href="<?= WEB_ROOT; ?>/stylesheets/main.css">
    <title>Create Task List</title>
</head>

<body>
    <h2>Create Task List</h2>

    <form method="post" action="<?= WEB_ROOT ?>/processTaskList">
        <label for="nombreLista">Nombre de la Lista:</label>
        <input type="text" name="nombreLista" required>
        <br>

        <label for="prioridad">Prioridad:</label>
        <select name="prioridad" required>
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
        </select>
        <br>

        <label for="tareas">Seleccione las Tareas:</label>
        <select name="tareas[]" multiple>
            <?php foreach ($this->tasksData['tasks'] as $task) : ?>
                <option value="<?= $task['task_id']; ?>"><?= $task['task_description']; ?></option>
            <?php endforeach; ?>
        </select>
        <br>

        <button type="submit">Crear Lista</button>
    </form>
</body>

</html>
