<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="<?php echo WEB_ROOT; ?>/stylesheets/main.css">
	<header>
        <nav>
            <a href= "<?php echo WEB_ROOT; ?>/test">HOME</a>
            <a href="<?php echo WEB_ROOT; ?>/application">LOG IN</a>
            <a href="<?php echo WEB_ROOT; ?>/logout" class="logout-link">LOG OUT</a>
        </nav>

    </header>
</head>

	<?php echo $this->content(); ?>

</body>
</html>

