<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="<?php echo WEB_ROOT; ?>/stylesheets/main.css">
</head>
<body>
<h1 class="page-title">To-do </h1>
<h2 class="sub-title">List </h2>
<a href="<?php echo WEB_ROOT; ?>/applicationRegister" class="btn-black">Sign Up</a>
<img class="lineas" src="<?php echo WEB_ROOT; ?>/images/lineasHomePage.png" alt="Descripción de la imagen">

	
</body>
</html>
