<!-- createTaskListForm.php -->

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Crear Lista de Tareas</title>
</head>
<body>
    <h1>Crear Lista de Tareas</h1>
    <form action="processTaskList.php" method="post">
        <label for="nombreLista">Nombre de la Lista:</label>
        <input type="text" id="nombreLista" name="nombreLista"><br><br>

        <label for="prioridad">Prioridad:</label>
        <select id="prioridad" name="prioridad">
            <option value="1">Prioridad 1</option>
            <option value="2">Prioridad 2</option>
            <option value="3">Prioridad 3</option>
        </select><br><br>

        <fieldset>
            <legend>Tareas Disponibles</legend>
            <?php foreach ($tasksData as $tarea) : ?>
                <input type="checkbox" id="tarea<?= $tarea['task_id'] ?>" name="tareas[]" value="<?= $tarea['task_id'] ?>">
                <label for="tarea<?= $tarea['task_id'] ?>"><?= $tarea['task_description'] ?></label><br>
            <?php endforeach; ?>
        </fieldset><br>

        <input type="submit" value="Crear Lista">
    </form>
</body>
</html>
