<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="stylesheet" href="<?= WEB_ROOT; ?>/stylesheets/main.css">
    <title>Create Task List</title>
</head>

<body>
    <h2>Create Task List</h2>

    <form method="post" action="<?= WEB_ROOT ?>/processTaskList">
        <label for="nombreLista">List Name:</label>
        <input type="text" name="nombreLista" required>
        <br>

        <label for="prioridad">Priority:</label>
        <select name="prioridad" required>
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
        </select>
        <br>

        <input type="hidden" name="usuario" value="<?= $_SESSION['username']; ?>">

        <label for="tareas">Select Tasks:</label>
        <select name="tareas[]" multiple>
            <?php 
            foreach ($this->tasksData['tasks'] as $task) : 
                if ($task['task_created_by'] === $_SESSION['username']) {
            ?>
                <option value="<?= $task['task_id']; ?>"><?= $task['task_description']; ?></option>
            <?php 
                } 
            endforeach; 
            ?>
        </select>
        <br>

        <button type="submit">Create List</button>
    </form>
</body>

</html>
