<!DOCTYPE html>
<html>
<head>
    <title>Create Task</title>
</head>
<body>
    <style>
        .btn {
            padding: 10px;
            background-color: #3498db;
            color: white;
            text-decoration: none;
            border: none;
            border-radius: 5px;
            display: inline-block;
            margin-right: 10px;
            font-size: 16px; 
        }

        .btn-secondary {
            background-color: #2980b9;
            font-size: 14px
        }

        .btn:hover {
            background-color: #2c3e50;
        }
    </style>
<h2>Create New Task</h2>
    <form method="post" action="<?= WEB_ROOT ?>/createTask">
    <label for="task_id">Task ID:</label>
        <input type="text" id="task_id" name="task_id"><br><br>

        <label for="task_description">Description:</label>
        <input type="text" id="task_description" name="task_description"><br><br>

        <label for="task_status">Status:</label>
        <select id="task_status" name="task_status">
            <option value="pending">Pending</option>
            <option value="in_progress">In Progress</option>
            <option value="completed">Completed</option>
        </select><br><br>

        <label for="task_priority">Priority:</label>
        <select id="task_priority"  name="task_priority"> 
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
        </select><br><br>

        <label for="task_assigned_to">Assigned To:</label> 
        <input type="text" id="task_assigned_to" name="task_assigned_to"><br><br>

        <label for="task_creation_date">Creation Date:</label>
        <input type="date" id="task_creation_date" name="task_creation_date"><br><br>

        <label for="task_deadline">Deadline:</label>
        <input type="date" id="task_deadline" name="task_deadline"><br><br>

        <label for="task_updated_at">Task Updated At:</label>
        <input type="text" id="task_updated_at" name="task_updated_at"><br><br>

        <label for="task_created_by">Task Created By:</label>
        <input type="text" id="task_created_by" name="task_created_by"><br><br>

        <label for="task_updated_by">Task Updated By:</label>
        <input type="text" id="task_updated_by" name="task_updated_by"><br><br>

        <input type="submit" value="Create Task" class="btn">
        <a href="<?= WEB_ROOT ?>/getTasks" class="btn btn-secondary">Go Back to Tasks</a>
    </form>
</body>
</html>
