<!DOCTYPE html>
<html>

<head>
    <link rel="stylesheet" href="<?php echo WEB_ROOT; ?>/stylesheets/main.css">
    <title>Delete Task List</title>
</head>

<body>
    <h2>Delete Task List</h2>

    <?php
    // Ruta del archivo nuevaLista.json
    $jsonFilePath = __DIR__ . '/../../../../db/nuevaLista.json';

    // Verificar si el archivo existe
    if (file_exists($jsonFilePath)) {
        // Leer el contenido del archivo
        $jsonContent = file_get_contents($jsonFilePath);

        // Decodificar el contenido JSON
        $listasExistentes = json_decode($jsonContent, true);

        // Verificar si la decodificación fue exitosa
        if ($listasExistentes !== null) {
            // Mostrar el formulario y las opciones
            echo '<form method="post" action="' . WEB_ROOT . '/deleteTaskList">';
            echo '<input type="hidden" name="_method" value="POST">';
            echo '<label for="taskListId">Select Task List to Delete:</label>';
            echo '<select id="taskListId" name="taskListId">';

            foreach ($listasExistentes as $taskList) {
                echo "<option value='" . $taskList['nombre'] . "'>" . $taskList['nombre'] . "</option>";
            }

            echo '</select>';
            echo '<button type="submit">Delete Task List</button>';
            echo '</form>';
        } else {
            // Mostrar un mensaje de error si la decodificación falla
            echo "<p>Error al cargar las listas.</p>";
        }
    } else {
        echo "<p>El archivo no existe en la ruta especificada: $jsonFilePath</p>";
    }
    ?>

    <button class="buttongt" onclick="location.href='<?= WEB_ROOT ?>/getTasks'">Back to Tasks</button>
</body>

</html>
