<!DOCTYPE html>
<html>
<head>
    <title>Delete Task</title>
</head>
<body>
    <h2>Delete Task</h2>
    <p>Are you sure you want to delete this task?</p>
    
    <form method="post" action="<?= WEB_ROOT ?>/deleteTask">
        <input type="hidden" name="task_id" value="<?php echo $task['task_id']; ?>">
        <input type="submit" value="Delete">
        <a href="<?= WEB_ROOT ?>/getTaskById?task_id=<?php echo $task['task_id']; ?>">Cancel</a>
    </form>
</body>
</html>
