<!DOCTYPE html>
<html>

<head>
    <link rel="stylesheet" href="<?php echo WEB_ROOT; ?>/stylesheets/main.css">
    <title>Delete Task List</title>
</head>

<body>
    <h2>Delete Task List</h2>

    <?php
    $jsonFilePath = __DIR__ . '/../../../../db/nuevaLista.json';

    if (file_exists($jsonFilePath)) {
        $jsonContent = file_get_contents($jsonFilePath);

        $listasExistentes = json_decode($jsonContent, true);

        if ($listasExistentes !== null) {
            echo '<form method="post" action="' . WEB_ROOT . '/deleteTaskList">';
            echo '<input type="hidden" name="_method" value="POST">';
            echo '<label for="taskListId">Select Task List to Delete:</label>';
            echo '<select id="taskListId" name="taskListId">';

            $username = isset($_SESSION['username']) ? $_SESSION['username'] : null;

            if ($username !== null) {
                foreach ($listasExistentes as $taskList) {
                    if (isset($taskList['usuario']) && $taskList['usuario'] === $username) {
                        echo "<option value='" . $taskList['nombre'] . "'>" . $taskList['nombre'] . "</option>";
                    }
                }
            } else {
                echo "<option>No se ha iniciado sesión</option>";
            }

            echo '</select>';
            echo '<button type="submit">Delete Task List</button>';
            echo '</form>';
        } else {
            echo "<p>Error al cargar las listas.</p>";
        }
    } else {
        echo "<p>El archivo no existe en la ruta especificada: $jsonFilePath</p>";
    }
    ?>

    <button class="buttongt" onclick="location.href='<?= WEB_ROOT ?>/getTasks'">Back to Tasks</button>
</body>

</html>
