<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Editar Nombre de Lista de Tareas</title>
</head>
<body>

<?php
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $selectedListName = $_POST['selectedListName'];
    $newListName = $_POST['newListName'];


    header("Location: http://localhost/Sprint3__TODOLIST-mergeList/web/showTaskList");
    exit();
}
?>

<form method="post" action="">
    <label for="selectedListName">Selecciona la lista de tareas a editar:</label>
    <select name="selectedListName" required>
        <?php
        $jsonFilePath = __DIR__ . '/../../../../db/nuevaLista.json';
        $jsonContent = file_get_contents($jsonFilePath);
        $taskLists = json_decode($jsonContent, true);

        foreach ($taskLists as $taskList) {
            echo "<option value=\"{$taskList['nombre']}\">{$taskList['nombre']}</option>";
        }
        ?>
    </select>

    <br>

    <label for="newListName">Nuevo nombre de la lista de tareas:</label>
    <input type="text" name="newListName" required>

    <br>

    <input type="submit" value="Editar Nombre de Lista">
</form>

</body>
</html>
