<form method="post" action="<?= WEB_ROOT ?>/updateTask">
        <!-- <label for="task_id">ID de Tarea:</label> -->
        <input type="hidden" id="task_id" name="task_id" value="<?php echo $this->taskData['task_id']; ?>" readonly>
        
        <label for="task_description">Description:</label>
        <input type="text" name="task_description" value="<?php echo $this->taskData['task_description']; ?>">
        
        <label for="task_status">Status:</label>
        <select id="task_status" name="task_status">
            <option value="pending" <?php echo ($this->taskData['task_status'] == 'pending') ? 'selected' : ''; ?>>Pending</option>
            <option value="in_progress" <?php echo ($this->taskData['task_status'] == 'in_progress') ? 'selected' : ''; ?>> In Progress</option>
            <option value="completed" <?php echo ($this->taskData['task_status'] == 'completed') ? 'selected' : ''; ?>>Completed</option>
        </select><br><br>

        <label for="task_creation_date">Creation Date:</label>
        <input type="date" id="task_creation_date" name="task_creation_date" value=<?php echo $this->taskData['task_creation_date']; ?> readonly> <br><br>

        <label for="task_deadline">Deadline:</label>
        <input type="date" id="task_deadline" name="task_deadline" value="<?php echo $this->taskData['task_deadline']; ?>"readonly><br><br>

        <label for="task_assigned_to">Assigned To :</label>
        <input type="text" id="task_assigned_to" name="task_assigned_to" value=<?php echo $this->taskData['task_assigned_to']; ?>><br><br>

        <label for="task_priority">Priority:</label>
        <select id="task_priority" name="task_priority">
            <option value= "1"<?php echo ($this->taskData['task_priority'] == 1) ? 'selected' : ''; ?>> 1</option>
            <option value="2"<?php echo ($this->taskData['task_priority'] == 2) ? 'selected' : ''; ?>> 2</option>
            <option value="3"<?php echo ($this->taskData['task_priority'] == 3) ? 'selected' : ''; ?>> 3</option>
        </select><br><br>

        <label for="task_updated_at">Task Updated At:</label>
        <input type="datetime-local" id="task_updated_at" name="task_updated_at" value="<?php echo $this->taskData['task_updated_at']; ?>"readonly><br><br>

        <label for="task_created_by">Task Created By:</label>
        <input type="text" id="task_created_by" name="task_created_by" value="<?php echo $this->taskData['task_created_by']; ?>"readonly><br><br>

        <label for="task_updated_by">Task Updated By:</label>
        <input type="text" id="task_updated_by" name="task_updated_by" value="<?php echo $this->taskData['task_updated_by']; ?>"><br><br>

    <button type="submit">Guardar cambios</button>
</form>     