<!DOCTYPE html>
<html>

<head>
<link rel="stylesheet" href="<?php echo WEB_ROOT; ?>/stylesheets/main.css">
<title>All Tasks</title>
    <style>
        table {
            border-collapse: collapse;
            width: 100%;
        }
        th,
        td {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
        }
        th {
            background-color: #f2f2f2;
        }
    </style>    
</head>

<body>
    <?php
    if (isset($this->allTasks['tasks']) && count($this->allTasks['tasks']) > 0) : ?>
        <table>
            <thead>
                <tr>
                    <th>Task ID</th>
                    <th>Description</th>
                    <th>Status</th>
                    <th>Priority</th>
                    <th>Assigned to</th>
                    <th>Creation Date</th>
                    <th>Deadline</th>
                    <th>Updated At</th>
                    <th>Created By</th>
                    <th>Updated By</th>

                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->allTasks['tasks'] as $task) : ?>
                    <tr>
                        <td><?php echo isset($task['task_id']) ? $task['task_id'] : ''; ?></td>
                        <td><?php echo isset($task['task_description']) ? $task['task_description'] : ''; ?></td>
                        <td><?php echo isset($task['task_status']) ? $task['task_status'] : ''; ?></td>
                        <td><?php echo isset($task['task_priority']) ? $task['task_priority'] : ''; ?></td>
                        <td><?php echo isset($task['task_assigned_to']) ? $task['task_assigned_to'] : ''; ?></td>
                        <td><?php echo isset($task['task_creation_date']) ? $task['task_creation_date'] : ''; ?></td>
                        <td><?php echo isset($task['task_deadline']) ? $task['task_deadline'] : ''; ?></td>
                        <td><?php echo isset($task['task_updated_at']) ? $task['task_updated_at'] : ''; ?></td>
                        <td><?php echo isset($task['task_created_by']) ? $task['task_created_by'] : ''; ?></td>
                        <td><?php echo isset($task['task_updated_by']) ? $task['task_updated_by'] : ''; ?></td>

                        <td>
                            <form method="post" action="<?= WEB_ROOT ?>/editTask">
                                <input type="hidden" name="task_id" value="<?php echo $task['task_id']; ?>">
                                <button class="buttongt" type="submit">Editar</button>
                            </form>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>

        <button class="buttongt" onclick="location.href='<?= WEB_ROOT ?>/createTask'">Create Task</button>
        <button class="buttongt" onclick="location.href='<?= WEB_ROOT ?>/getTaskById'">Search Task By Id</button>
        

    <?php else : ?>
        <p>No tasks available.</p>
    <?php endif; ?>
</body>

</html>