<!DOCTYPE html>
<html>

<head>
    <link rel="stylesheet" href="<?php echo WEB_ROOT; ?>/stylesheets/main.css">
    <title>All Tasks</title>
</head>

<body>
    <h1>All Tasks</h1>
    <?php
    if (isset($_SESSION['user_id']) && !empty($_SESSION['user_id'])) {
        $user_id = $_SESSION['username'];

        // Filtrar las tareas basadas en el usuario logeado
        $tasks_assigned_to_user = [];
        foreach ($this->allTasks['tasks'] as $task) {
            if ($task['task_created_by'] == $user_id) {
                $tasks_assigned_to_user[] = $task;
            }
        }

        if (count($tasks_assigned_to_user) > 0) :
            //if (isset($this->allTasks['tasks']) && count($this->allTasks['tasks']) > 0) : ?>
            <table class="table-tasks">
                <thead>
                    <tr>
                        <th>Task ID</th>
                        <th>Description</th>
                        <th>Status</th>
                        <th>Priority</th>
                        <th>Assigned to</th>
                        <th>Creation Date</th>
                        <th>Deadline</th>
                        <th>Updated At</th>
                        <th>Created By</th>
                        <th>Updated By</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($tasks_assigned_to_user as $task) : //foreach ($this->allTasks['tasks'] as $task) : ?>
                        <tr>
                            <td><?php echo isset($task['task_id']) ? $task['task_id'] : ''; ?></td>
                            <td><?php echo isset($task['task_description']) ? $task['task_description'] : ''; ?></td>
                            <td><?php echo isset($task['task_status']) ? $task['task_status'] : ''; ?></td>
                            <td class="priority-<?php echo isset($task['task_priority']) ? $task['task_priority'] : ''; ?>">
                                <span><?php echo isset($task['task_priority']) ? $task['task_priority'] : ''; ?></td></span>
                            <td><?php echo isset($task['task_assigned_to']) ? $task['task_assigned_to'] : ''; ?></td>
                            <td><?php echo isset($task['task_creation_date']) ? $task['task_creation_date'] : ''; ?></td>
                            <td><?php echo isset($task['task_deadline']) ? $task['task_deadline'] : ''; ?></td>
                            <td><?php echo isset($task['task_updated_at']) ? $task['task_updated_at'] : ''; ?></td>
                            <td><?php echo isset($task['task_created_by']) ? $task['task_created_by'] : ''; ?></td>
                            <td><?php echo isset($task['task_updated_by']) ? $task['task_updated_by'] : ''; ?></td>

                            <td>
                                <form method="post" action="<?= WEB_ROOT ?>/editTask">
                                    <input type="hidden" name="task_id" value="<?php echo $task['task_id']; ?>">
                                    <button class="buttongt" type="submit">Editar</button>
                                </form>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>

            <button class="buttongt" onclick="location.href='<?= WEB_ROOT ?>/createTask'">Create New Task</button>
            <button class="buttongt" onclick="location.href='<?= WEB_ROOT ?>/getTaskById'">Search Task By Id</button>

            <?php else : ?>
    <p>No tasks available for this user.</p>
    <button class="buttongt" onclick="location.href='<?php echo WEB_ROOT; ?>/createTask'">Create New Task</button>
<?php endif; ?>

<?php } else { ?>
    <p>Sesión no iniciada. Por favor, inicia sesión para acceder a tus tareas.</p>
    <button class="buttongt" onclick="location.href='<?php echo WEB_ROOT; ?>/createTask'">Create New Task</button>
<?php } ?>

</body>

</html>
