<!DOCTYPE html>
<html>
<head>
    <title>All Tasks</title>
</head>
<body>
    <?php 
    if (isset($_GET['task_id']) && !empty($_GET['task_id'])) {
        $requestedTaskId = strval($_GET['task_id']); 
        //var_dump($requestedTaskId);
        if (isset($this->allTasks['tasks']) && count($this->allTasks['tasks']) > 0) {
            foreach ($this->allTasks['tasks'] as $task) {
                //var_dump($task);
                if ($task['task_id'] === $requestedTaskId) {//paso ambos datos a int por antes compara strign con int
                    echo "This is your Task: ";
                    ?>
                    <h2>Task:</h2>
                    <p><strong>Task ID:</strong> <?php echo $task['task_id']; ?></p>
                    <p><strong>Description:</strong> <?php echo $task['task_description']; ?></p>
                    <p><strong>Status:</strong> <?php echo $task['task_status']; ?></p>
                    <p><strong>Creation Date:</strong> <?php echo $task['task_creation_date']; ?></p>
                    <p><strong>Deadline:</strong> <?php echo $task['task_deadline']; ?></p>
                    <p><strong>User ID:</strong> <?php echo $task['task_created_by']; ?></p>
                    <p><strong>Priority:</strong> <?php echo $task['task_priority']; ?></p>
                    <p><strong>Assigned to:</strong> <?php echo $task['task_assigned_to']; ?></p>
                    
                    <?php
                    break;
                }
            }
        } else {
            echo "<p>Task not found.</p>";
        }
    } else {
        echo "<p>Please provide a task ID.</p>";
    }
    ?>

    <?php if (!isset($task) || $task['task_id'] !== $requestedTaskId): ?>
        <form method="GET" action="">
            <label for="task_id">Search Task by ID:</label>
            <input type="text" id="task_id" name="task_id">
            <button type="submit">Search</button>
        </form>
    <?php endif; ?>
    <?php if (isset($task) && $task['task_id'] === $requestedTaskId): ?>
        <form method="post" action="<?= WEB_ROOT ?>/deleteTask">
            <input type="hidden" name="task_id" value="<?php echo $task['task_id']; ?>">
            <input type="submit" value="Delete Task">
        </form>
    <?php endif; ?>
    <a href="<?php echo WEB_ROOT; ?>/getTasks">See tasks</a>
</body>
</html>
