<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sistema de Login</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
        }
        .login {
            text-align: center;
            margin-top: 50px;
        }
        .login form {
            margin-bottom: 20px;
        }
        .login a {
            display: inline-block;
            padding: 10px 20px;
            background-color: #007bff;
            color: white;
            text-decoration: none;
            border-radius: 5px;
        }
        .login a:hover {    
            background-color: #0056b3;
        }
    </style>

</head>
<body>
    <div class="login">
        <?php //var_dump($_SESSION['username']);
        if(!isset($_SESSION['user_id']) || empty($_SESSION['user_id'])): ?>
            <h1>Sistema de Login</h1>
            <form action="" method="post"> 
                <label for="username">Usuario</label>
                <input type="text" name="username" placeholder="Usuario" id="username" required>
                <label for="password">Contraseña</label>
                <input type="password" name="password" placeholder="Contraseña" id="password" required>
                <input type="submit" value="Acceder">
            </form>
            <a href="<?= WEB_ROOT; ?>/applicationRegister">Registro</a>
        <?php else: ?>
            <a href="<?php echo WEB_ROOT; ?>/getTasks">Ver tareas</a>
        <?php endif; ?>
    </div>
    <?php echo $this->mensaje; ?>
</body>
</html>
