<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="<?php echo WEB_ROOT; ?>/stylesheets/main.css">
    <title>Sign Up</title>
</head>
<body>
    <?php if(!isset($_SESSION['user_id']) || empty($_SESSION['user_id'])): ?>
        <h1>SIGN UP</h1>
        <form action="" method="post">
            <p><?php echo $this->mensaje; ?></p>
            <label for= "username">Usuario</label>
            <input type = "text" name="username" placeholder="user" id= "username" required><br>
            <label for= "password">Contraseña</label>
            <input type="password" name="password" placeholder="Contraseña" id="password" required><br>
            <label for= "email">Email</label>
            <input type="email" name="email" placeholder="email" id="email" required><br>
            <input type="submit" value="Enviar">
        </form>
        <?php else: ?>
            <h1>Bienvenido, <?php echo isset($_SESSION['username']) ? $_SESSION['username'] : 'Usuario'; ?></h1>
            <a href="<?php echo WEB_ROOT; ?>/createTask" class="btn">Crear Tareas</a>
            <a href="<?= WEB_ROOT ?>/getTasks">Ver tareas</a>
            <?php endif; ?>
</body>
</html>
