<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign Up</title>
</head>
<body>
    <h1>SIGN UP</h1>
    <form action="" method="post">
        <p><?php echo $this->mensaje; ?></p>
        <label for= "username">Usuario</label>
        <input type = "text" name="username" placeholder="user" id= "username" required><br>
        <label for= "password">Contraseña</label>
        <input type="password" name="password" placeholder="Contraseña" id="password" required><br>
        <label for= "email">Email</label>
        <input type="email" name="email" placeholder="email" id="email" required><br>
        <input type="submit" value="Enviar">
    </form>
    <a href="<?= WEB_ROOT ?>/getTasks">Ver tareas</a>
</body>
</html>
