
<head>
</head>
<body>
<h1>REGISTER</h1>
<form action="" method="post">

<p><?php echo $this->mensaje; ?></p>
<label for= "username"></label>
<input type = "text" name="username" 
placeholder="user" id= "username" required>
<br>
<label for= "password"></label>
<input type="password" name="password"
placeholder="Contraseña" id="password" required>
<br>
<label for= "email"></label>
<input type="email" name="email"
placeholder="email" id="email" required>
<br>
<input type="submit" value="enviar">
</body>