<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lista de Tareas</title>
    <link rel="stylesheet" href="<?php echo WEB_ROOT; ?>/stylesheets/main.css">
    <style>
    </style>
</head>
<body>
    <table class="table-tasks">
        <thead>
            <tr>
                <th>List Name</th>
                <th>Priority</th>
                <th>Tasks</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->userTaskLists as $taskList) : ?>
                <tr>
                    <td><?php echo $taskList['nombre']; ?></td>
                    <td><?php echo $taskList['prioridad']; ?></td>
                    <td>
                        <ul>
                            <?php foreach ($taskList['tareas'] as $taskName) : ?>
                                <li><?php echo $taskName; ?></li>
                            <?php endforeach; ?>
                        </ul>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <button class="buttongt" onclick="location.href='<?= WEB_ROOT ?>/createTaskListForm'">Create Tasks Lists </button>
                <button class="buttongt" onclick="location.href='<?= WEB_ROOT ?>/deleteTaskList'">Delete Tasks Lists </button>
                <button class="buttongt" onclick="location.href='<?= WEB_ROOT ?>/editTaskListForm'">Edit Task List</button>
</body>
</html>
