<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<header>
        <nav>
            <a href= "<?php echo WEB_ROOT; ?>/test">HOME</a>
            <a href="<?php echo WEB_ROOT; ?>/application">LOGIN</a>
            <a href="<?php echo WEB_ROOT; ?>/applicationRegister">SIGN UP</a>
        </nav>

    </header>
</head>
<body>
	<?php echo $this->content(); ?>

</body>
</html>

